require: rubocop-rspec
AllCops:
  Include:
    - '**/Rakefile'
  Exclude:
    - 'bin/**/*'
    - 'config/**/*'
    - 'log/**/*'
    - 'tmp/**/*'
    - 'spec/lint/rubocop_spec.rb'
  TargetRubyVersion: 2.3

Metrics/AbcSize:
  Max: 30

Metrics/ClassLength:
  Max: 100

Metrics/CyclomaticComplexity:
  Max: 10

Metrics/LineLength:
  Max: 100
  AllowURI: true
  URISchemes: http

Metrics/MethodLength:
  Max: 10

Metrics/ModuleLength:
  Max: 300

Metrics/PerceivedComplexity:
  Max: 10
